apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ipl-ingress
  namespace: murali-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ipl-service
            port:
              number: 80

      - path: /netflix
        pathType: Prefix
        backend:
          service:
            name: netflix-service
            port:
              number: 81
