apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ipl-deployment
  namespace: murali-ns
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ipl
  template:
    metadata:
      labels:
        app: ipl
    spec:
      containers:
        - name: ipl-container
          image: muralisocial123/ipl:latest
          ports:
            - containerPort: 3000

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: netflix-deployment
  namespace: murali-ns
spec:
  replicas: 5
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
        - name: netflix-container
          image: muralisocial123/netflix-25.v1:latest
          ports:
            - containerPort: 80